import catalogProducts from "@/assets/catalog-products.jpg";
import phoneBlue from "@/assets/phone-blue-gallery.jpg";

export type CatalogItem = {
  brand: string;
  name: string;
  slug: string;
  category: "Mobile" | "Audio" | "Electronics" | "Footwear" | "Wearables" | "Accessories";
  monthly: string;
  price: string;
  mrp?: string;
  tag?: string;
  rating: number;
  image: string;
  imagePosition?: string;
  tone: string;
  storage: string[];
};

export const catalog: CatalogItem[] = [
  {
    brand: "Samsung",
    name: "Galaxy A57 5G",
    slug: "galaxy-a57-5g",
    category: "Mobile",
    monthly: "₹2,326/mo",
    price: "₹49,999",
    mrp: "₹58,999",
    tag: "15% off",
    rating: 4.8,
    image: phoneBlue,
    tone: "bg-product-blue",
    storage: ["128GB", "256GB"],
  },
  {
    brand: "Apple",
    name: "iPhone 18 Pro",
    slug: "iphone-18-pro",
    category: "Mobile",
    monthly: "₹7,673/mo",
    price: "₹1,64,900",
    tag: "New Launch",
    rating: 4.9,
    image: catalogProducts,
    imagePosition: "14% 20%",
    tone: "bg-product-coral",
    storage: ["256GB", "512GB", "1TB"],
  },
  {
    brand: "Apple",
    name: "iPhone 18 Pro Max",
    slug: "iphone-18-pro-max",
    category: "Mobile",
    monthly: "₹8,371/mo",
    price: "₹1,79,900",
    tag: "New Launch",
    rating: 4.9,
    image: catalogProducts,
    imagePosition: "14% 20%",
    tone: "bg-product-coral",
    storage: ["256GB", "512GB", "1TB"],
  },
  {
    brand: "Apple",
    name: "AirPods 5",
    slug: "airpods-5",
    category: "Audio",
    monthly: "₹693/mo",
    price: "₹14,900",
    tag: "New Launch",
    rating: 4.8,
    image: catalogProducts,
    imagePosition: "22% 82%",
    tone: "bg-muted",
    storage: ["Standard"],
  },
  {
    brand: "Google",
    name: "Pixel 11",
    slug: "pixel-11",
    category: "Mobile",
    monthly: "₹3,839/mo",
    price: "₹82,499",
    mrp: "₹89,999",
    rating: 4.7,
    image: catalogProducts,
    imagePosition: "76% 20%",
    tone: "bg-product-sky",
    storage: ["128GB", "256GB"],
  },
  {
    brand: "Samsung",
    name: "Galaxy S26",
    slug: "galaxy-s26",
    category: "Mobile",
    monthly: "₹4,374/mo",
    price: "₹93,999",
    mrp: "₹1,17,999",
    rating: 4.8,
    image: catalogProducts,
    imagePosition: "76% 20%",
    tone: "bg-product-lilac",
    storage: ["256GB", "512GB"],
  },
  {
    brand: "Sony",
    name: "WF-C510 Truly Wireless",
    slug: "sony-wf-c510",
    category: "Audio",
    monthly: "₹209/mo",
    price: "₹4,500",
    mrp: "₹8,990",
    tag: "49% off",
    rating: 4.6,
    image: catalogProducts,
    imagePosition: "22% 82%",
    tone: "bg-muted",
    storage: ["Standard"],
  },
  {
    brand: "Sennheiser",
    name: "ACCENTUM Open",
    slug: "sennheiser-accentum-open",
    category: "Audio",
    monthly: "₹279/mo",
    price: "₹5,990",
    mrp: "₹12,990",
    rating: 4.6,
    image: catalogProducts,
    imagePosition: "22% 82%",
    tone: "bg-product-sun",
    storage: ["Standard"],
  },
  {
    brand: "Marshall",
    name: "Emberton III",
    slug: "marshall-emberton-iii",
    category: "Audio",
    monthly: "₹744/mo",
    price: "₹15,999",
    mrp: "₹17,999",
    rating: 4.8,
    image: catalogProducts,
    imagePosition: "78% 82%",
    tone: "bg-product-sage",
    storage: ["Standard"],
  },
  {
    brand: "Marshall",
    name: "Major V",
    slug: "marshall-major-v",
    category: "Audio",
    monthly: "₹605/mo",
    price: "₹12,999",
    mrp: "₹14,999",
    rating: 4.7,
    image: catalogProducts,
    imagePosition: "78% 82%",
    tone: "bg-product-coral",
    storage: ["Standard"],
  },
  {
    brand: "Samsung",
    name: "Galaxy Buds4",
    slug: "galaxy-buds4",
    category: "Audio",
    monthly: "₹791/mo",
    price: "₹16,999",
    mrp: "₹22,999",
    rating: 4.7,
    image: catalogProducts,
    imagePosition: "22% 82%",
    tone: "bg-product-sky",
    storage: ["Standard"],
  },
  {
    brand: "Samsung",
    name: "Galaxy S26 Ultra",
    slug: "galaxy-s26-ultra",
    category: "Mobile",
    monthly: "₹6,282/mo",
    price: "₹1,34,999",
    mrp: "₹1,49,999",
    tag: "10% off",
    rating: 4.9,
    image: catalogProducts,
    imagePosition: "76% 20%",
    tone: "bg-muted",
    storage: ["256GB", "512GB"],
  },
  {
    brand: "Apple",
    name: "MacBook Neo",
    slug: "macbook-neo",
    category: "Electronics",
    monthly: "₹3,252/mo",
    price: "₹69,999",
    tag: "Popular",
    rating: 4.7,
    image: catalogProducts,
    imagePosition: "14% 20%",
    tone: "bg-product-sun",
    storage: ["256GB", "512GB"],
  },
  {
    brand: "Nothing",
    name: "Phone 4a",
    slug: "nothing-phone-4a",
    category: "Mobile",
    monthly: "₹1,912/mo",
    price: "₹41,099",
    rating: 4.5,
    image: catalogProducts,
    imagePosition: "76% 20%",
    tone: "bg-product-lilac",
    storage: ["128GB", "256GB"],
  },
  {
    brand: "Apple",
    name: "MacBook Air M5",
    slug: "macbook-air-m5",
    category: "Electronics",
    monthly: "₹5,840/mo",
    price: "₹1,24,900",
    rating: 4.8,
    image: catalogProducts,
    imagePosition: "50% 18%",
    tone: "bg-product-blue",
    storage: ["256GB", "512GB"],
  },
  {
    brand: "Samsung",
    name: "Galaxy Z Fold 8",
    slug: "galaxy-z-fold-8",
    category: "Mobile",
    monthly: "₹8,299/mo",
    price: "₹1,77,999",
    rating: 4.8,
    image: catalogProducts,
    imagePosition: "76% 20%",
    tone: "bg-product-lilac",
    storage: ["256GB", "512GB"],
  },
  {
    brand: "Motorola",
    name: "Edge 70",
    slug: "motorola-edge-70",
    category: "Mobile",
    monthly: "₹1,666/mo",
    price: "₹39,999",
    rating: 4.5,
    image: phoneBlue,
    tone: "bg-product-sage",
    storage: ["128GB", "256GB"],
  },
  {
    brand: "vivo",
    name: "T5X 5G",
    slug: "vivo-t5x-5g",
    category: "Mobile",
    monthly: "₹1,208/mo",
    price: "₹28,999",
    rating: 4.5,
    image: phoneBlue,
    tone: "bg-product-sky",
    storage: ["128GB", "256GB"],
  },
  {
    brand: "mokobara",
    name: "Transit Backpack",
    slug: "mokobara-transit-backpack",
    category: "Accessories",
    monthly: "₹375/mo",
    price: "₹7,999",
    rating: 4.5,
    image: catalogProducts,
    imagePosition: "50% 76%",
    tone: "bg-product-lilac",
    storage: ["Standard"],
  },
  {
    brand: "EDT",
    name: "Everyday Wireless Earbuds",
    slug: "edt-wireless-earbuds",
    category: "Audio",
    monthly: "₹249/mo",
    price: "₹5,299",
    rating: 4.4,
    image: catalogProducts,
    imagePosition: "22% 82%",
    tone: "bg-muted",
    storage: ["Standard"],
  },
  {
    brand: "Assembly",
    name: "Everyday Work Tote",
    slug: "assembly-work-tote",
    category: "Accessories",
    monthly: "₹229/mo",
    price: "₹4,899",
    rating: 4.5,
    image: catalogProducts,
    imagePosition: "78% 82%",
    tone: "bg-product-sun",
    storage: ["Standard"],
  },
  {
    brand: "Fitbit",
    name: "Charge 6",
    slug: "fitbit-charge-6",
    category: "Wearables",
    monthly: "₹625/mo",
    price: "₹13,399",
    rating: 4.6,
    image: catalogProducts,
    imagePosition: "78% 82%",
    tone: "bg-product-sage",
    storage: ["Standard"],
  },
  {
    brand: "Yonex",
    name: "Power Cushion Eclipsion",
    slug: "yonex-eclipsion",
    category: "Footwear",
    monthly: "₹695/mo",
    price: "₹14,899",
    rating: 4.6,
    image: catalogProducts,
    imagePosition: "58% 80%",
    tone: "bg-product-blue",
    storage: ["Standard"],
  },
  ...(
    [
      [
        "Women Trendy Heels",
        "women-trendy-heels",
        "₹80/mo",
        "₹1,709",
        "14% 80%",
        "bg-product-coral",
      ],
      ["Men's Solid Brown", "mens-solid-brown", "₹154/mo", "₹3,299", "45% 78%", "bg-product-sun"],
      ["Blue Sneakers", "blue-sneakers", "₹80/mo", "₹1,729", "58% 80%", "bg-product-blue"],
      ["Women Kitten Heel", "women-kitten-heel", "₹73/mo", "₹1,574", "38% 80%", "bg-product-lilac"],
      [
        "Stylish Men's Sneaker",
        "stylish-mens-sneaker",
        "₹80/mo",
        "₹1,729",
        "67% 80%",
        "bg-product-sage",
      ],
    ] as const
  ).map(([name, slug, monthly, price, imagePosition, tone]) => ({
    brand: "Clog London",
    name,
    slug,
    category: "Footwear" as const,
    monthly,
    price,
    rating: 4.6,
    image: catalogProducts,
    imagePosition,
    tone,
    storage: ["Standard"],
  })),
];

export const brands = [...new Set(catalog.map((product) => product.brand))];
export const categories = [
  "Mobile",
  "Audio",
  "Electronics",
  "Footwear",
  "Wearables",
  "Accessories",
] as const;

export function getProduct(slug: string) {
  return catalog.find((product) => product.slug === slug);
}
