import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { LocateFixed } from "lucide-react";
import { PageShell } from "@/components/shop/site-shell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export const Route = createFileRoute("/checkout/address")({ head: () => ({ meta: [{ title: "Shipping Address — BytePe" }, { name: "description", content: "Enter your delivery address for your BytePe order." }, { property: "og:title", content: "Shipping Address — BytePe" }, { property: "og:description", content: "Add delivery information and continue to payment." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: AddressPage });
const fields = [["Your Full Name", "Full name"], ["Flat No. / House no.", "Address line"], ["Your email id", "Email"], ["Area, Street, Sector", "Area"], ["Your mobile number", "Mobile number"], ["Landmark (optional)", "Landmark"], ["Pincode", "Pincode"], ["Area/City", "City"], ["State", "State"]];
function AddressPage() { const navigate = useNavigate({ from: "/checkout/address" }); return <PageShell footer={false}><main className="mx-auto max-w-[1100px] px-4 py-7 md:px-8"><Link to="/cart" className="text-sm">← Cart Summary</Link><div className="mx-auto mt-4 flex max-w-xl items-center"><span className="size-4 rounded-full border-2 border-primary bg-background" /><span className="h-px flex-1 bg-border" /><span className="size-4 rounded-full border-2 border-border bg-background" /></div><div className="mx-auto mt-2 flex max-w-[570px] justify-between text-xs text-muted-foreground"><span>Address</span><span>Payment</span></div><h1 className="mt-10 font-display text-3xl">Shipping Address</h1><Button variant="outline" className="mt-5 w-full rounded-full"><LocateFixed className="size-4 text-primary" />Use my current location</Button><form className="mt-5 grid gap-4 md:grid-cols-2" onSubmit={(event) => { event.preventDefault(); navigate({ to: "/checkout/payment" }); }}>{fields.map(([label, placeholder], index) => <label key={label} className={index === fields.length - 1 ? "md:col-start-2" : ""}><span className="mb-1 block text-xs">{label}{!label.includes("optional") && <b className="text-primary">*</b>}</span><Input required={!label.includes("optional")} placeholder={placeholder} className="h-11" /></label>)}<fieldset className="md:col-start-2"><legend className="text-sm">Choose Address Type</legend><div className="mt-2 flex gap-5 text-sm">{["Home", "Office", "Other"].map((type, index) => <label key={type} className="flex items-center gap-2"><input type="radio" name="type" defaultChecked={index === 0} className="accent-[var(--primary)]" />{type}</label>)}</div></fieldset><Button type="submit" className="mt-4 w-full rounded-full md:col-span-2">Save & Proceed</Button></form></main></PageShell>; }
